import React from "react";
import { CalNum } from "./CalNum";

export const CalRow = () => {
  return (
    <div className="grid grid-cols-7 gap-x-3 gap-y-2 mt-4">
      <CalNum
        Number={"1"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"2"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"3"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"4"}
        isactive={false}
        bg={"/images/events/cal-row-bg.png"}
      />
      <CalNum
        Number={"5"}
        isactive={false}
        bg={"/images/events/cal-row-bg.png"}
      />
      <CalNum
        Number={"6"}
        isactive={false}
        bg={"/images/events/cal-row-bg.png"}
      />
      <CalNum
        Number={"7"}
        isactive={true}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"8"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"9"}
        isactive={false}
        bg={"/images/events/cal-row-bg.png"}
      />
      <CalNum
        Number={"10"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"11"}
        isactive={true}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"12"}
        isactive={false}
        bg={"/images/events/cal-row-bg.png"}
      />
      <CalNum
        Number={"13"}
        isactive={false}
        bg={"/images/events/cal-row-bg.png"}
      />
      <CalNum
        Number={"14"}
        isactive={false}
        bg={"/images/events/cal-row-bg.png"}
      />
      <CalNum
        Number={"15"}
        isactive={true}
        bg={"/images/events/cal-row-bg.png"}
      />
      <CalNum
        Number={"16"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"17"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"18"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"19"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"20"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"21"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"22"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"23"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"24"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"25"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"26"}
        isactive={true}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"27"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"28"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"29"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"30"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
      <CalNum
        Number={"31"}
        isactive={false}
        bg={"/images/events/main-event.jpg"}
      />
    </div>
  );
};
